workflows:
  android-debug-workflow:
    name: NokiaVxpEmulator - Debug Build
    max_build_duration: 60

    environment:
      java: 17
      vars:
        PACKAGE_NAME: "com.nokia.vxp"

    scripts:
      - name: Build Debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk